@api = http://localhost:4000/products

#### get all products
GET {{api}}




#### GET Product
GET  {{api}}/6289b607a24b50057b95a4f9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODliNjNjYTI0YjUwMDU3Yjk1YTRmYyIsImlzUm9vdCI6ZmFsc2UsImlzQWRtaW4iOmZhbHNlLCJpc1VzZXIiOnRydWUsImlhdCI6MTY1MzE5MjI1M30.kZ2XGlCQ9kVxqzhXZRKcNf1prRRA9rkLi67ekPjs6M4





#### CREATE Product
POST {{api}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODliNjNjYTI0YjUwMDU3Yjk1YTRmYyIsImlzUm9vdCI6ZmFsc2UsImlzQWRtaW4iOmZhbHNlLCJpc1VzZXIiOnRydWUsImlhdCI6MTY1MzE5NDY3N30.wecNVuo4F-tP8W8k486riv6N-NpKaLAwt2vw8Ll0AG0

{
    "name": "product20",
    "price": 10.30,
    "description": "product1 description",
    "quantity": 10
}



# UPDATING PRODUCT

PUT {{{{api}}}}/6289b607a24b50057b95a4f9


